### ISSUE TITLE
rcases がエラーになる

### ISSUE THREAD

**Issue by Seasawher** [yuma-mizuno/lean-math-workshop#14]
Lean4 web で試したところ，下記コードがエラーになります:

```lean
import Std

example : P ∨ Q → (P → R) → (Q → R) → R := by
  intro h hPR hQR
  rcases h with hP | hQ
  · apply hPR hP 
  · apply hQR hQ
```

https://lean.math.hhu.de/#code=import%20Std%0D%0A%0D%0Aexample%20%3A%20P%20%E2%88%A8%20Q%20%E2%86%92%20(P%20%E2%86%92%20R)%20%E2%86%92%20(Q%20%E2%86%92%20R)%20%E2%86%92%20R%20%3A%3D%20by%0D%0A%20%20intro%20h%20hPR%20hQR%0D%0A%20%20rcases%20h%20with%20hP%20%7C%20hQ%0D%0A%20%20%C2%B7%20apply%20hPR%20hP%20%0D%0A%20%20%C2%B7%20apply%20hQR%20hQ

**Comment by yuma-mizuno** [comment]
`variable (P Q R : Prop)`が抜けているからです。
